version: '3.8'

services:
  tg-standup-bot:
    image: ghcr.io/123hi123/tg-standup-bot:latest
    container_name: tg-standup-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DEFAULT_SIT_DURATION=${DEFAULT_SIT_DURATION:-45}
      - DEFAULT_STAND_DURATION=${DEFAULT_STAND_DURATION:-5}
    # 如果需要持久化數據，可以掛載 volume
    # volumes:
    #   - ./data:/app/data
